"use client";

import { FormEvent, ReactElement, useEffect, useMemo, useState } from "react";
import Image from "next/image";
import { supabase } from "../../../lib/supabase";

type Application = { id: string; created_at: string; full_name: string; voice_type: string; email: string; phone: string; musical_background: string | null; status: string };
type EventRecord = { id: string; title: string; category: string; event_date: string; event_time: string; venue: string; description: string | null };
type NewsRecord = { id: string; created_at: string; title: string; category: string; content: string };
type ContactMessage = { id: string; created_at: string; full_name: string; email: string; subject: string; message: string; status: string };
type MediaItem = { id: string; created_at: string; media_type: "Photos" | "Videos"; url: string; caption: string; category: string };
type Tab = "applications" | "events" | "news" | "contacts" | "media";

const tabs: { id: Tab; label: string }[] = [
  { id: "applications", label: "Applications" }, { id: "events", label: "Events & Calendar" },
  { id: "news", label: "News & Announcements" }, { id: "contacts", label: "Contact Messages" }, { id: "media", label: "Media & Gallery" },
];
const emptyEvent = { title: "", category: "Services", event_date: "", event_time: "", venue: "", description: "" };
const emptyNews = { title: "", category: "Announcement", content: "", publication_date: "" };

export default function AdminPage() {
  const [sessionReady, setSessionReady] = useState(false);
  const [userEmail, setUserEmail] = useState("");
  const [activeTab, setActiveTab] = useState<Tab>("applications");
  const [applications, setApplications] = useState<Application[]>([]);
  const [events, setEvents] = useState<EventRecord[]>([]);
  const [news, setNews] = useState<NewsRecord[]>([]);
  const [contacts, setContacts] = useState<ContactMessage[]>([]);
  const [media, setMedia] = useState<MediaItem[]>([]);
  const [loginEmail, setLoginEmail] = useState("");
  const [loginPassword, setLoginPassword] = useState("");
  const [applicationFilter, setApplicationFilter] = useState("All");
  const [applicationSearch, setApplicationSearch] = useState("");
  const [eventForm, setEventForm] = useState(emptyEvent);
  const [editingEventId, setEditingEventId] = useState<string | null>(null);
  const [newsForm, setNewsForm] = useState(emptyNews);
  const [editingNewsId, setEditingNewsId] = useState<string | null>(null);
  const [mediaForm, setMediaForm] = useState({ media_type: "Photos", url: "", caption: "", category: "General" });
  const [mediaFile, setMediaFile] = useState<File | null>(null);
  const [message, setMessage] = useState("");
  const [busy, setBusy] = useState(false);

  function toast(text: string) { setMessage(text); window.setTimeout(() => setMessage(""), 4000); }

  async function loadProtectedData() {
    const { data: { session } } = await supabase.auth.getSession();
    if (!session?.user) { setUserEmail(""); setSessionReady(true); return; }
    setUserEmail(session.user.email ?? "");
    const [applicationResult, eventResult, newsResult, contactResult, mediaResult] = await Promise.all([
      supabase.from("applications").select("id,created_at,full_name,voice_type,email,phone,musical_background,status").order("created_at", { ascending: false }),
      supabase.from("events").select("id,title,category,event_date,event_time,venue,description").order("event_date", { ascending: true }),
      supabase.from("news").select("id,created_at,title,category,content").order("created_at", { ascending: false }),
      supabase.from("contact_messages").select("id,created_at,full_name,email,subject,message,status").order("created_at", { ascending: false }),
      supabase.from("media_items").select("id,created_at,media_type,url,caption,category").order("created_at", { ascending: false }),
    ]);
    if (applicationResult.error) toast(applicationResult.error.message);
    if (eventResult.error) toast(eventResult.error.message);
    if (newsResult.error) toast(newsResult.error.message);
    if (contactResult.error) toast(contactResult.error.message);
    if (mediaResult.error) toast(mediaResult.error.message);
    setApplications(applicationResult.data ?? []); setEvents(eventResult.data ?? []); setNews(newsResult.data ?? []); setContacts(contactResult.data ?? []); setMedia(mediaResult.data ?? []); setSessionReady(true);
  }

  useEffect(() => { void loadProtectedData(); const { data: listener } = supabase.auth.onAuthStateChange(() => void loadProtectedData()); return () => listener.subscription.unsubscribe(); }, []);

  async function signIn(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(""); const { error } = await supabase.auth.signInWithPassword({ email: loginEmail, password: loginPassword }); setBusy(false); if (error) toast(error.message); }

  async function updateApplicationStatus(id: string, status: "accepted" | "rejected") { setBusy(true); const { error } = await supabase.from("applications").update({ status }).eq("id", id); setBusy(false); if (error) toast(error.message); else { setApplications((current) => current.map((item) => item.id === id ? { ...item, status } : item)); toast(`Application status updated to ${status === "accepted" ? "Accepted" : "Rejected"}.`); } }

  async function saveEvent(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const payload = { ...eventForm }; const result = editingEventId ? await supabase.from("events").update(payload).eq("id", editingEventId) : await supabase.from("events").insert(payload); setBusy(false); if (result.error) toast(result.error.message); else { toast(editingEventId ? "Event successfully updated." : "Event successfully published."); setEventForm(emptyEvent); setEditingEventId(null); void loadProtectedData(); } }
  async function deleteEvent(id: string) { setBusy(true); const { error } = await supabase.from("events").delete().eq("id", id); setBusy(false); if (error) toast(error.message); else { setEvents((current) => current.filter((item) => item.id !== id)); toast("Event deleted."); } }

  async function saveNews(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const payload = { title: newsForm.title, category: newsForm.category, content: newsForm.content, ...(newsForm.publication_date ? { created_at: new Date(newsForm.publication_date).toISOString() } : {}) }; const result = editingNewsId ? await supabase.from("news").update(payload).eq("id", editingNewsId) : await supabase.from("news").insert(payload); setBusy(false); if (result.error) toast(result.error.message); else { toast(editingNewsId ? "News article updated." : "News article published."); setNewsForm(emptyNews); setEditingNewsId(null); void loadProtectedData(); } }
  async function deleteNews(id: string) { setBusy(true); const { error } = await supabase.from("news").delete().eq("id", id); setBusy(false); if (error) toast(error.message); else { setNews((current) => current.filter((item) => item.id !== id)); toast("News article deleted."); } }
  async function unpublishNews(id: string) { setBusy(true); const { error } = await supabase.from("news").delete().eq("id", id); setBusy(false); if (error) toast(error.message); else { setNews((current) => current.filter((item) => item.id !== id)); toast("News article unpublished."); } }

  async function toggleContactStatus(contact: ContactMessage) { const status = contact.status === "replied" ? "unread" : "replied"; setBusy(true); const { error } = await supabase.from("contact_messages").update({ status }).eq("id", contact.id); setBusy(false); if (error) toast(error.message); else { setContacts((current) => current.map((item) => item.id === contact.id ? { ...item, status } : item)); toast(`Message marked as ${status === "replied" ? "Replied" : "Unread"}.`); } }
  async function saveMedia(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); let mediaUrl = mediaForm.url; if (mediaFile) { const filePath = `${crypto.randomUUID()}-${mediaFile.name.replace(/[^a-zA-Z0-9._-]/g, "-")}`; const upload = await supabase.storage.from("media").upload(filePath, mediaFile, { upsert: false, contentType: mediaFile.type }); if (upload.error) { setBusy(false); toast(upload.error.message); return; } mediaUrl = supabase.storage.from("media").getPublicUrl(filePath).data.publicUrl; } const { error } = await supabase.from("media_items").insert({ ...mediaForm, url: mediaUrl }); setBusy(false); if (error) toast(error.message); else { toast("Media item added to the gallery."); setMediaForm({ media_type: "Photos", url: "", caption: "", category: "General" }); setMediaFile(null); void loadProtectedData(); } }
  async function deleteMedia(id: string) { setBusy(true); const { error } = await supabase.from("media_items").delete().eq("id", id); setBusy(false); if (error) toast(error.message); else { setMedia((current) => current.filter((item) => item.id !== id)); toast("Media item removed."); } }

  const filteredApplications = useMemo(() => applications.filter((item) => (applicationFilter === "All" || item.status === applicationFilter.toLowerCase()) && item.full_name.toLowerCase().includes(applicationSearch.toLowerCase())), [applications, applicationFilter, applicationSearch]);
  const formInput = (label: string, value: string, onChange: (value: string) => void, type = "text") => <label>{label}<input required={label !== "Description"} type={type} value={value} onChange={(event) => onChange(event.target.value)} /></label>;

  if (!sessionReady) return <main className="admin-login"><div className="admin-login-card"><Image className="admin-logo" src="/Namirembe cathedral logo.png" alt="Namirembe Cathedral logo" width={72} height={80} priority /><h1>Checking<br /><em>your session.</em></h1></div></main>;
  if (!userEmail) return <main className="admin-login"><div className="admin-login-card"><Image className="admin-logo" src="/Namirembe cathedral logo.png" alt="Namirembe Cathedral logo" width={72} height={80} priority /><p className="admin-kicker">Namirembe Cathedral Choir</p><h1>Admin<br /><em>Portal</em></h1><p className="admin-muted">Secure access for the choir team.</p><form onSubmit={signIn}><label>Email Address<input required type="email" value={loginEmail} onChange={(event) => setLoginEmail(event.target.value)} placeholder="admin@example.com" /></label><label>Password<input required type="password" value={loginPassword} onChange={(event) => setLoginPassword(event.target.value)} placeholder="Password" /></label><button className="admin-primary" disabled={busy} type="submit">{busy ? "Signing in..." : "Sign In to Admin Portal"}</button>{message && <p className="admin-error" role="alert">{message}</p>}</form></div></main>;

  return <main className="admin-portal"><aside className="admin-sidebar"><div className="admin-brand"><Image className="admin-sidebar-logo" src="/Namirembe cathedral logo.png" alt="Namirembe Cathedral logo" width={44} height={50} /><div><strong>NAMIREMBE</strong><small>CHOIR ADMIN PORTAL</small></div></div><nav aria-label="Administration navigation">{tabs.map((tab) => <button className={activeTab === tab.id ? "active" : ""} key={tab.id} onClick={() => setActiveTab(tab.id)}>{tab.label}</button>)}</nav><button className="admin-sidebar-logout" onClick={() => supabase.auth.signOut()}>Log Out</button></aside><div className="admin-content"><header className="admin-topbar"><div><p className="admin-kicker">Administrative workspace</p><h1>Welcome, Mr. John Ssekibaala</h1></div><div className="admin-user"><span>Administrator</span><button className="admin-outline" onClick={() => supabase.auth.signOut()}>Log Out</button></div></header>{message && <div className="admin-toast" role="status">{message}</div>}<section className="admin-panel admin-tab-panel">{activeTab === "applications" && <ApplicationsTab applications={filteredApplications} filter={applicationFilter} search={applicationSearch} setFilter={setApplicationFilter} setSearch={setApplicationSearch} onStatus={updateApplicationStatus} busy={busy} />}{activeTab === "events" && <EventsTab events={events} form={eventForm} setForm={setEventForm} editingId={editingEventId} setEditingId={setEditingEventId} onSave={saveEvent} onDelete={deleteEvent} busy={busy} formInput={formInput} />}{activeTab === "news" && <NewsTab news={news} form={newsForm} setForm={setNewsForm} editingId={editingNewsId} setEditingId={setEditingNewsId} onSave={saveNews} onDelete={deleteNews} onUnpublish={unpublishNews} busy={busy} />}{activeTab === "contacts" && <ContactsTab contacts={contacts} onToggle={toggleContactStatus} busy={busy} />}{activeTab === "media" && <MediaTab media={media} form={mediaForm} setForm={setMediaForm} mediaFile={mediaFile} setMediaFile={setMediaFile} onSave={saveMedia} onDelete={deleteMedia} busy={busy} />}</section></div></main>;
}

function ApplicationsTab({ applications, filter, search, setFilter, setSearch, onStatus, busy }: { applications: Application[]; filter: string; search: string; setFilter: (value: string) => void; setSearch: (value: string) => void; onStatus: (id: string, status: "accepted" | "rejected") => void; busy: boolean }) { return <><p className="admin-kicker">Choir Applications Management</p><h2>Applicant pipeline</h2><div className="admin-toolbar"><input placeholder="Search by name" value={search} onChange={(event) => setSearch(event.target.value)} /><select value={filter} onChange={(event) => setFilter(event.target.value)}><option>All</option><option>Pending</option><option>Accepted</option><option>Rejected</option></select></div><div className="admin-table-wrap"><table><thead><tr><th>Applicant</th><th>Voice</th><th>Email / Phone</th><th>Musical Background</th><th>Date Submitted</th><th>Status / Actions</th></tr></thead><tbody>{applications.map((item) => <tr key={item.id}><td>{item.full_name}</td><td>{item.voice_type}</td><td>{item.email}<br />{item.phone}</td><td>{item.musical_background || "Not provided"}</td><td>{new Date(item.created_at).toLocaleDateString()}</td><td><span className={`admin-status ${item.status}`}>{item.status}</span><div className="admin-actions"><button disabled={busy || item.status === "accepted"} onClick={() => onStatus(item.id, "accepted")}>Accept</button><button disabled={busy || item.status === "rejected"} onClick={() => onStatus(item.id, "rejected")}>Reject</button></div></td></tr>)}</tbody></table>{!applications.length && <p className="admin-muted">No applications match your filters.</p>}</div></>; }

function EventsTab({ events, form, setForm, editingId, setEditingId, onSave, onDelete, busy, formInput }: { events: EventRecord[]; form: typeof emptyEvent; setForm: (value: typeof emptyEvent) => void; editingId: string | null; setEditingId: (value: string | null) => void; onSave: (event: FormEvent<HTMLFormElement>) => void; onDelete: (id: string) => void; busy: boolean; formInput: (label: string, value: string, onChange: (value: string) => void, type?: string) => ReactElement }) { return <><p className="admin-kicker">Events & Calendar Management</p><h2>{editingId ? "Edit event" : "Add an event"}</h2><form className="admin-form" onSubmit={onSave}>{formInput("Title", form.title, (value) => setForm({ ...form, title: value }))}<label>Category<select value={form.category} onChange={(event) => setForm({ ...form, category: event.target.value })}><option>Services</option><option>Concerts</option><option>Rehearsals</option><option>Special Celebrations</option></select></label><div className="admin-form-row">{formInput("Date", form.event_date, (value) => setForm({ ...form, event_date: value }), "date")}{formInput("Time", form.event_time, (value) => setForm({ ...form, event_time: value }), "time")}</div>{formInput("Venue", form.venue, (value) => setForm({ ...form, venue: value }))}<label>Description<textarea value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} rows={3} /></label><button className="admin-primary" disabled={busy} type="submit">{editingId ? "Update event" : "Publish event"}</button>{editingId && <button className="admin-outline admin-cancel" type="button" onClick={() => { setEditingId(null); setForm(emptyEvent); }}>Cancel</button>}</form><h2 className="admin-subheading">Upcoming events</h2><div className="admin-record-list">{events.map((item) => <article key={item.id}><div><strong>{item.title}</strong><span>{item.category} · {item.event_date} · {item.event_time} · {item.venue}</span><p>{item.description}</p></div><div className="admin-actions"><button onClick={() => { setEditingId(item.id); setForm({ title: item.title, category: item.category, event_date: item.event_date, event_time: item.event_time, venue: item.venue, description: item.description || "" }); }}>Edit</button><button onClick={() => onDelete(item.id)}>Delete</button></div></article>)}</div></>; }

function NewsTab({ news, form, setForm, editingId, setEditingId, onSave, onDelete, onUnpublish, busy }: { news: NewsRecord[]; form: typeof emptyNews; setForm: (value: typeof emptyNews) => void; editingId: string | null; setEditingId: (value: string | null) => void; onSave: (event: FormEvent<HTMLFormElement>) => void; onDelete: (id: string) => void; onUnpublish: (id: string) => void; busy: boolean }) { return <><p className="admin-kicker">News & Announcements CMS</p><h2>{editingId ? "Edit article" : "Publish an article"}</h2><form className="admin-form" onSubmit={onSave}><label>Title<input required value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} /></label><label>Category<input required value={form.category} onChange={(event) => setForm({ ...form, category: event.target.value })} placeholder="Announcement, Press Release, Concert Report" /></label><label>Content Body<textarea required rows={5} value={form.content} onChange={(event) => setForm({ ...form, content: event.target.value })} /></label><label>Publication Date<input type="date" value={form.publication_date} onChange={(event) => setForm({ ...form, publication_date: event.target.value })} /></label><button className="admin-primary" disabled={busy} type="submit">{editingId ? "Update article" : "Publish article"}</button></form><h2 className="admin-subheading">Published posts</h2><div className="admin-record-list">{news.map((item) => <article key={item.id}><div><strong>{item.title}</strong><span>{item.category} · {new Date(item.created_at).toLocaleDateString()}</span><p>{item.content}</p></div><div className="admin-actions"><button onClick={() => { setEditingId(item.id); setForm({ title: item.title, category: item.category, content: item.content, publication_date: item.created_at.slice(0, 10) }); }}>Edit</button><button onClick={() => onUnpublish(item.id)}>Unpublish</button><button onClick={() => onDelete(item.id)}>Delete</button></div></article>)}</div></>; }

function ContactsTab({ contacts, onToggle, busy }: { contacts: ContactMessage[]; onToggle: (contact: ContactMessage) => void; busy: boolean }) { return <><p className="admin-kicker">Contact Enquiries Inbox</p><h2>Public enquiries</h2><div className="admin-record-list">{contacts.map((contact) => <article key={contact.id}><div><strong>{contact.subject}</strong><span>{contact.full_name} · {contact.email} · {new Date(contact.created_at).toLocaleString()}</span><p>{contact.message}</p></div><div className="admin-actions"><a href={`mailto:${contact.email}?subject=Re: ${encodeURIComponent(contact.subject)}`}>Reply</a><button disabled={busy} onClick={() => onToggle(contact)}>{contact.status === "replied" ? "Mark Unread" : "Mark Replied"}</button></div></article>)}</div>{!contacts.length && <p className="admin-muted">No contact enquiries yet.</p>}</>; }

function MediaTab({ media, form, setForm, mediaFile, setMediaFile, onSave, onDelete, busy }: { media: MediaItem[]; form: { media_type: string; url: string; caption: string; category: string }; setForm: (value: { media_type: string; url: string; caption: string; category: string }) => void; mediaFile: File | null; setMediaFile: (file: File | null) => void; onSave: (event: FormEvent<HTMLFormElement>) => void; onDelete: (id: string) => void; busy: boolean }) { return <><p className="admin-kicker">Media & Gallery Management</p><h2>Add media</h2><form className="admin-form" onSubmit={onSave}><label>Type<select value={form.media_type} onChange={(event) => setForm({ ...form, media_type: event.target.value })}><option>Photos</option><option>Videos</option></select></label>{form.media_type === "Photos" && <label>Upload image from your files<input type="file" accept="image/*" onChange={(event) => setMediaFile(event.target.files?.[0] ?? null)} /></label>}<label>{form.media_type === "Photos" ? "Image URL (optional)" : "YouTube Embed URL"}<input required={!mediaFile} type="url" value={form.url} onChange={(event) => setForm({ ...form, url: event.target.value })} /></label>{mediaFile && <p className="admin-file-name">Selected file: {mediaFile.name}</p>}<label>Category<input required value={form.category} onChange={(event) => setForm({ ...form, category: event.target.value })} placeholder="Worship, Rehearsal, Concert" /></label><label>Caption<input required value={form.caption} onChange={(event) => setForm({ ...form, caption: event.target.value })} /></label><button className="admin-primary" disabled={busy} type="submit">{busy ? "Uploading..." : "Add to gallery"}</button></form><h2 className="admin-subheading">Current gallery items</h2><div className="admin-record-list">{media.map((item) => <article key={item.id}><div><strong>{item.caption}</strong><span>{item.media_type} · {item.category}</span><p>{item.url}</p></div><button onClick={() => onDelete(item.id)}>Delete</button></article>)}</div></>; }
